<a href="https://colab.research.google.com/github/VaishnavWani/Mahchine_Learning/blob/main/Multilinear_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
# from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
data = pd.read_excel("/content/SalesData.xlsx")

In [ ]:
data.head()

   Advertising  Temperature  Gender Region   Sales
0        57.45        25.82  Female   West  433.23
1        47.93        38.39    Male  South  386.91
2        59.72        24.37    Male   West  518.70
3        72.85        18.73    Male   West  466.22
4        46.49        17.55  Female  North  345.77

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Advertising  700 non-null    float64
 1   Temperature  700 non-null    float64
 2   Gender       700 non-null    object
 3   Region       700 non-null    object
 4   Sales        700 non-null    float64
dtypes: float64(3), object(2)
memory usage: 27.5+ KB

In [ ]:
dummie_gender = pd.get_dummies(data.Gender, drop_first=True).astype(int)
dummie_Region = pd.get_dummies(data.Region, drop_first=True).astype(int)

In [ ]:
data = data.drop(["Gender", "Region"], axis=1)

In [ ]:
data

     Advertising  Temperature   Sales
0          57.45        25.82  433.23
1          47.93        38.39  386.91
2          59.72        24.37  518.70
3          72.85        18.73  466.22
4          46.49        17.55  345.77
..           ...          ...     ...
695        45.36        31.48  362.62
696        54.89        19.22  414.98
697        31.23        22.23  324.88
698        63.86        39.60  460.30
699        47.23        24.74  355.94

[700 rows x 3 columns]

In [ ]:
data = pd.concat([data,dummie_gender, dummie_Region], axis=1)

In [ ]:
data

     Advertising  Temperature   Sales  Male  North  South  West
0          57.45        25.82  433.23     0      0      0     1
1          47.93        38.39  386.91     1      0      1     0
2          59.72        24.37  518.70     1      0      0     1
3          72.85        18.73  466.22     1      0      0     1
4          46.49        17.55  345.77     0      1      0     0
..           ...          ...     ...   ...    ...    ...   ...
695        45.36        31.48  362.62     0      0      1     0
696        54.89        19.22  414.98     0      1      0     0
697        31.23        22.23  324.88     0      0      0     1
698        63.86        39.60  460.30     1      0      0     0
699        47.23        24.74  355.94     1      0      0     1

[700 rows x 7 columns]

In [ ]:
x = data.drop("Sales", axis=1)
y = data.Sales

In [ ]:
xtrain,xtest, ytrain, ytest = train_test_split(x,y, random_state=20, test_size=0.2)

In [ ]:
xtrain = sm.add_constant(xtrain)
xtest = sm.add_constant(xtest)

In [ ]:
xtrain.head()

     const  Advertising  Temperature  Male  North  South  West
346    1.0        28.28        35.22     0      1      0     0
91     1.0        64.53        31.66     1      0      1     0
299    1.0        59.44        34.58     1      0      0     1
129    1.0        42.45        27.75     0      0      0     0
695    1.0        45.36        31.48     0      0      1     0

In [ ]:
mod = sm.OLS(ytrain, xtrain).fit()

In [ ]:
print(mod.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.802
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     372.7
Date:                Thu, 25 Jun 2026   Prob (F-statistic):          1.21e-190
Time:                        17:44:26   Log-Likelihood:                -2789.8
No. Observations:                 560   AIC:                             5594.
Df Residuals:                     553   BIC:                             5624.
Df Model:                           6
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const         124.4064      8.699     14.301      0.000     107.319     141.493
Advertising     4.6756      0.101     46.237      0.000       4.477       4.874
Temperature     0.2806      0.192      1.464      0.144      -0.096       0.657
Male           12.6317      3.028      4.172      0.000       6.685      18.579
North         -18.8811      4.290     -4.401      0.000     -27.308     -10.454
South          -4.6967      4.534     -1.036      0.301     -13.603       4.210
West           23.2612      4.535      5.129      0.000      14.354      32.169
==============================================================================
Omnibus:                        0.171   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.918   Jarque-Bera (JB):                0.077
Skew:                          -0.015   Prob(JB):                        0.962
Kurtosis:                       3.049   Cond. No.                         371.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.